apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-result-mongo-deployment
  labels:
    app: next-result-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-result-mongo
  template:
    metadata:
      labels:
        app: next-result-mongo
    spec:
      containers:
      - name: next-result-mongo
        image: mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: next-result-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
